#!/bin/bash

showHelp() {

  echo "-------------------------------------"
  echo "CLI Dice Roller"
  echo
  echo "Usage: diceroller [OPTION] [INT] [HD] [MOD] [--sep] [FLAG] "
  echo
  echo "Options:"
  echo "--help     Displays this help message"
  echo " dn        Rolls an n sided dice"
  echo "INT: how many times you want the dice to rolled and added together."
  echo "HD: HD of monsters appearing. Takes an INT."
  echo "MOD: adds a + or - number to the roll. Defaults to 0"
  echo "--sep: allows for each die roll to be printed seperately. Die rolls are not combined."
  echo "FLAG: Default is false. Set to true to set -x"
  echo "-------------------------------------"

}

dieType=$1

numRolls=${2:-1}

monHd=${3:-1}

modifier=${4:-0}


# Array to copy to clipboard
declare -a diceArray=()

#Gets OS name
unamestr=$(uname)

if [[ $6 == "true" ]]; then
  set -x
fi

if [[ $1 == "--help" ]]; then
  showHelp
  exit 0
fi

total=0
faces="${dieType#d}"
totalMonsterHp=0

sepRoll() {
    for ((i = 0; i < numRolls; i++)); do
        for ((j =0; j < monHd; j++)); do
            RESULT=$((RANDOM % faces + 1 + $modifier))
            totalMonsterHp=$((totalMonsterHp + RESULT ))
        done
        diceArray+=("$totalMonsterHp")
        echo "Roll $((i + 1)): $dieType = $totalMonsterHp"
        totalMonsterHp=0
    done
}

singleRoll() {

    for ((i = 0; i < numRolls; i++)); do
        RESULT=$((RANDOM % faces + 1 + modifier))
        total=$((total + RESULT))
    done
    echo "Total = $total"
}

if [[ $5 == "--sep" ]]; then
    sepRoll
else
    singleRoll
fi

# Pipes to clipboard
if [[ "$unamestr" == "Darwin" ]]; then
  echo "${diceArray[@]}" | pbcopy
elif [[ "$unamestr" == "Linux" ]]; then
  echo "${diceArray[@]}" | xclip -selection clipboard
fi
