#!/bin/bash

readout=${3:-false}

if [ "$readout" == "true" ]; then
    set -x
fi

showHelp() {

	echo "-------------------------------------"
	echo "CLI Dice Roller"
	echo
	echo "Usage: diceroller [OPTION] [OPTION 2] [FLAG] "
	echo
	echo "Options:"
	echo "--help     Displays this help message"
	echo " d4        Rolls a d4"
	echo " d6        Rolls a d6"
	echo " d8        Rolls a d8"
	echo " d10       Rolls a d10"
	echo " d12       Rolls a d12"
	echo " d20       Rolls a d20"
	echo "OPTION 2"
	echo "INT: how many times you want the dice to rolled and added together."
	echo "FLAG: Default is false. Set to true to set -x"
	echo "-------------------------------------"

}

if [[ $1 == "--help" ]]; then
	showHelp
	exit 0
fi

dieType=$1
numRolls=${2:-1}	
total=0

for (( i=0; i<numRolls; i++ )); do

	if [ "$dieType" == "d4" ]; then
 	   	RESULT=$(( RANDOM % 4 + 1 ))
	elif [ "$dieType" == "d6" ]; then
    		RESULT=$(( RANDOM % 6 + 1 ))
	elif [ "$dieType" == "d8" ]; then
	    	RESULT=$(( RANDOM % 8 + 1 ))
	elif [ "$dieType" == "d10" ]; then
	    	RESULT=$(( RANDOM % 10 + 1 ))
	elif [ "$dieType" == "d12" ]; then
	    	RESULT=$(( RANDOM % 12 + 1 ))
	elif [ "$dieType" == "d20" ]; then
	    	RESULT=$(( RANDOM % 20 + 1 ))
	else
        	echo "Error: Unsupported die type."
        	exit 1
    	fi

	total=$(( total + RESULT ))

done

echo "---------------------------------"
echo "Total Roll Result for $numRolls rolls of $dieType = $total"
echo "---------------------------------"
